### ISSUE TITLE
Make this open source

### ISSUE THREAD

**Issue by AaronDewes** [netbirdio/management-integrations#14]
Right now, Netbird's server depends on this repo.

This repository does not have a LICENSE file. As such, the main self-hosted netbird executable can not be considered fully open source, because it includes this proprietary code.

I'd suggest adding a license to this repository.

**Comment by AaronDewes** [comment]
Thank you for fixing this. This repository seems to be just a "polyfill" that replaces the places where paid features would be.

By making it GPL, you are effectively relicensing netbird itself to the GPL (because it includes GPL software, it has to be GPL too). Is that intentional? If yes, I'd appreciate if you could mention it in the main repository and replace the license there.

**Comment by mlsmaycon** [comment]
we are looking into the BSD 3 compatibility with GPL and will give you feedback soon.
